jobs:
  # ... jobs Spring Boot existants ...

  # NOUVEAU JOB : Flask
  flask-build-and-push:
    runs-on: ubuntu-latest
    needs: test-and-build  # Attend Spring Boot
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Flask image
      uses: docker/build-push-action@v5
      with:
        context: ./flask-app  # ← Dossier Flask
        file: ./flask-app/Dockerfile
        push: true
        tags: |
          laksh1929/flask-app:latest
          laksh1929/flask-app:${{ github.sha }}