services:
  flask-app:
    image: laksh1929/flask-app:latest  # ← Image Docker Hub
    ports:
      - "5001:5000"
    environment:
      - MYSQL_HOST=mysql-db  # ← MySQL dans le conteneur
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DB=geekprofile
    depends_on:
      - mysql-db

  mysql-db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=geekprofile
    volumes:
      - mysql_prod_data:/var/lib/mysql

volumes:
  mysql_prod_data: